django_fc/django_fc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django_fc import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url (r"^delete_project/", views.delete_project, name = 'delete_project'),
    url (r"^edit_project/", views.edit_project, name = 'edit_project'),
    url (r"^toggle_mode/", views.toggle_stt_session_mode, name = 'toggle_mode'),
    url (r"^edit_settings/", views.edit_settings, name = 'edit_settings'),
    url(r"^select_project/(?P<name>[^\"*]*)", views.select_project, name="select_project"),
    url(r"^new_project/", views.new_project, name="new_project"),
    url(r"^fw_move_back/", views.fw_move_back, name="fw_move_back"),
    url(r"^fw_move_forward/", views.fw_move_forward, name="fw_move_forward"),
    url(r"^fw_move_to_start/", views.fw_move_to_start, name="fw_move_to_start"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^$", views.HomePage.as_view(), name="home"),

    url(r"^fcards/", include ('fcards.urls', namespace='fcards')),
    url(r"^upload/", include ('upload.urls', namespace='upload')),
    url(r"^text/"  , include ('text.urls'  , namespace='text')),


]

django_fc/text/urls.py
from django.conf.urls import url

from . import views

app_name='text'

urlpatterns = [
    url(r"^generate_src_file/", views.generate_src_file, name="generate_src_file"),
    url(r"^download_source_file/(?P<file_name>[^\"*]*)", views.download_source_file, name="download_source_file"),
    url(r"^work_with_text/(?P<file_name>[^\"*]*)", views.work_with_text, name="work_with_text"),
    url(r"^delete_file/(?P<file_name>[^\"*]+)/", views.delete_file, name="delete_file"),
    url(r"^save_file/(?P<file_name>[^\"*]+)/", views.save_file, name="save_file"),
]

django_fc/text/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from fcards.models import Project

# Create your models here.
class MyTextFilesModel (models.Model):
    user = models.ForeignKey(User, related_name="text_files", on_delete=models.CASCADE)
    project = models.ForeignKey (Project, related_name="text_files", on_delete=models.CASCADE, default=0)
    file_name = models.CharField (max_length=32)
    current = models.BooleanField (default = False)

django_fc/text/forms.py
from django import forms

class WorkWithTextForm (forms.Form):
    action_choises = {
        ('overwrite', 'overwrite the vocabulary')
      , ('append', 'append to existing vocabulary')
      , ('add_dates', 'add new dated sections')
    }
    #action = forms.ChoiceField(widget=forms.RadioSelect, choices=action_choises, initial='add_dates')

    save_file = forms.BooleanField (
        widget=forms.CheckboxInput,
        initial=True,
        label="Save file upon \"Submit Citations\"",
        required = False,

        )

    def __init__(self, txt, file_name,  *args, **kwargs):
        super(WorkWithTextForm, self).__init__(*args, **kwargs)

        label = ''
        long_txt_widget = forms.Textarea (
                attrs = {
                    'class' : 'form-control',
                    'rows' : 25,
                    'overflow-y' : 'scroll',
                    'overflow-x' : 'scroll',
                    'ID':'text_area',
                }
        )

        file_name_widget = forms.TextInput (
                attrs = {
                    'class' : 'form-control',
                    'ID':'file_name_box'
                }
        )

        self.fields ['file_name'] = forms.CharField (initial = file_name, label = 'File Name', widget = file_name_widget)
        self.fields ['text'] = forms.CharField (initial = txt, label = label, widget = long_txt_widget)



class GenerateSourceForm (forms.Form):

    def __init__(self, txt,  *args, **kwargs):
        super(GenerateSourceForm, self).__init__(*args, **kwargs)

        label = ''
        long_txt_widget = forms.Textarea (
                attrs = {
                    'class' : 'form-control',
                    'rows' : 25,
                    'overflow-y' : 'scroll',
                    'overflow-x' : 'scroll',
                    'ID':'text_area',
                }
        )

        file_name_widget = forms.TextInput (
                attrs = {
                    'class' : 'form-control',
                    'ID':'file_name_box'
                }
        )

        self.fields ['file_name'] = forms.CharField (label = 'File Name', widget = file_name_widget)
        self.fields ['text'] = forms.CharField (initial = txt, label = label, widget = long_txt_widget)

django_fc/text/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic import TemplateView, FormView, RedirectView
from django.urls import reverse
import codecs

from . import forms
from . import models


from fc_engine.db_voc import dbVoc
from fc_engine.settings import Settings
from fcards.models import VocEntry
from fcards.models import FCSettings
from .models import MyTextFilesModel
import fcards
from common.db_voc2voc_entry_db import db_voc2voc_entry_db, save_file
from common.db_voc2voc_entry_db import make_src_current, make_src_non_current, make_current_non_current

def work_with_text (request, *args, **kwargs):

    file_name = kwargs ['file_name']
    if len (file_name) > 0:
        project_id = request.session ['project_id']
        raw_file_name = file_name + '_' + str (request.user.id)
        new_raw_file_name = file_name + '_' + str (request.user.id) +  '_' + str (project_id)

        if os.path.isfile (new_raw_file_name):
            fin = codecs.open (new_raw_file_name, 'r', 'utf-8');
            txt = fin.read ()
        else:
            try:

                #print ("mydebug>>> work_with_text: last_file : {}".format (last_file))
                fin = codecs.open (raw_file_name, 'r', 'utf-8');
                txt = fin.read ()


            except:
                txt = ''
                file_name = ''
    else:
        txt = ''
    form = forms.WorkWithTextForm (txt, file_name)


    if request.method == 'POST':
        form = forms.WorkWithTextForm ('', '', request.POST)
        if 'submit_cits' in form.data:
            if form.is_valid ():

                txt = form. cleaned_data ['text']
                file_name = form.cleaned_data ['file_name']
                save_the_file = form.cleaned_data ['save_file']

                stt = Settings ()
                stt.from_json (request.session ['stt'])

                new_db_voc = dbVoc ()
                new_db_voc.from_text (txt, stt.extract_sentences)

                project_id = request.session ['project_id']
                if save_the_file:
                    save_file (txt, file_name, request.user.id, project_id)
                    make_src_current (file_name, request.user.id, project_id)
                else:
                    make_current_non_current (request.user.id, project_id)


                #action = request.POST ['action']
                action = 'overwrite'
                db_voc2voc_entry_db (action, new_db_voc, request.user.id, project_id)
            else:
                print ("Form invalid")

            return  HttpResponseRedirect (reverse ("home"))
        else:

            txt = request.POST ['text']
            #print ('txt: ' + txt)
            new_file_name = request.POST ['file_name'].strip ()
            #print ('new_file_name: ' + new_file_name)

            if len (new_file_name) > 0: # need more thorough check here
                project_id = request.session ['project_id']

                save_file (txt, new_file_name, request.user.id, project_id)
                make_src_non_current (new_file_name, request.user.id, project_id)

                #need to check here is new_file_name is valid

                return  HttpResponseRedirect (reverse ("text:work_with_text", kwargs={'file_name' : new_file_name}))


    return render (request, 'work_with_text.html', {'form':form, 'file_name':file_name})

import os

def delete_file (request, *args, **kwargs):

    print ('mydebug>>> delete_file called')
    file_name = kwargs ['file_name']
    print ('mydebug>>> delete_file : file_name : {}'.format (file_name))

    raw_file_name = file_name + '_' + str (request.user.id) + '_' + str (request.session ['project_id'])

    if os.path.isfile (raw_file_name):
        os.remove (raw_file_name)
        db_entries = MyTextFilesModel.objects.filter (file_name=file_name)
        if len (db_entries) > 1:
            print ("text.views.delete_file: [W] : there were more than one entries in file db with file_name: " + file_name)
        db_entries.delete ()


    else:
        print ('mydebug>>> delete_file : {} doesn\'t exist'.format (file_name))

    return  HttpResponseRedirect (reverse ("home"))

def generate_src_file (request):

    project_id = request.session ['project_id']
    all_voc = fcards.models.all_to_dbvoc (request.user.id, project_id)

    txt = ''
    for date in all_voc.dateL:
        txt += '\nlesson: ' + date + '\n\n'
        for ID in all_voc.date2idL [date]:

            vdbe = all_voc.id2vdbe [ID]

            ctxL = vdbe.ctxs.split ('|')
            citL = vdbe.cits.split ('|')
            strout = ctxL [0]
            for i in range (len (citL)):
                strout += citL [i]
                strout += ctxL [i + 1]
            txt += strout + '\n'

    form = forms.GenerateSourceForm (txt)
    if request.method == 'POST':

        form = forms.GenerateSourceForm ('', request.POST)

        if form.is_valid ():

            txt = form. cleaned_data ['text']
            file_name = form.cleaned_data ['file_name']
            save_file (txt, file_name, request.user.id, project_id)
            make_src_current (file_name, request.user.id, project_id)

        else:
            print ("Form invalid")

        return  HttpResponseRedirect (reverse ("home"))

    return render (request, 'generate_src_file.html', {'form':form})



from django.http import FileResponse


def download_source_file (request, *args, **kwargs):
    file_name = kwargs ['file_name']
    if len (file_name) > 0:
        project_id = request.session ['project_id']
        raw_file_name = file_name + '_' + str (request.user.id)
        new_raw_file_name = file_name + '_' + str (request.user.id) +  '_' + str (project_id)

    if os.path.isfile (new_raw_file_name):
        response = FileResponse(open(new_raw_file_name, 'rb'))
        response['Content-Disposition'] = 'attachment; filename={}'.format (file_name)
        return response
    else:
        response = FileResponse(open(raw_file_name, 'rb'), filename = file_name, as_attachment = True)

    return  HttpResponseRedirect (reverse ("home"))

django_fc/text/templates/generate_src_file.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Work with text</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <div class="container mycontent">

      <div class="jumbodtron">
        <form method="POST">

          <div class="row">
              <div class="col-md-9">
                {{form.as_p}}
                {% csrf_token %}
              </div>

              <div class="col-md-3">

                <h1>
                  <input type='submit' class="btn  btn-primary" name="submit_cits" value="Approve"/>
                  <a href="{% url 'home' %}" class="btn btn-primary">Cancel</a>
                </h1>

              </div>
          </div>

       </form>
      </div>

    </div>

  </body>
</html>

django_fc/text/templates/work_with_text.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Work with text</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <div class="container mycontent">

      <div class="jumbodtron">
        <form method="POST">

          <div class="row">
              <div class="col-md-9">
                {{form.as_p}}
                {% csrf_token %}
              </div>

              <div class="col-md-3">

                <h1>
                    <input ID='date_btn'
                      onclick="insert_date();"
                      class="btn  btn-primary"
                      value="Insert Time Stamp"/>
                </h1>

                {% if file_name %}
                   <a latent_href="{% url 'text:delete_file' file_name=file_name %}"
                      ID='delete_file_btn'
                      class="btn btn-danger"
                      disabled>
                        Delete {{ file_name }}
                   </a>
                   <label for='enable_delete_chkbox'>Enable Delete button</label>
                   <input type='checkbox'
                          ID='enable_delete_chkbox'
                          onclick="enable_delete_file()" />

                {% endif %}
                <h1>
                <input  type='submit'

                   ID="save_file_btn"
                   class="btn btn-primary"
                   value="Save file"
                   name="save_file"
                />
                </h1>
                <h1>
                  <input type='submit' class="btn  btn-primary" name="submit_cits" value="Submit Citaitons"/>
                  <a href="{% url 'home' %}" class="btn btn-primary">Cancel</a>
                </h1>

              </div>
          </div>

       </form>
      </div>

    </div>
    <script>

        function insert_date ()
        {
            var TextAreaControl = document.getElementById ('text_area');
            TextAreaControl.focus ();

            var txt = TextAreaControl.value;
            var selStart = TextAreaControl.selectionStart;
            var selEnd = TextAreaControl.selectionEnd;
            //alert ("start: " + selStart + "\nend: " + selEnd)
            var date_str = '\ndate: ' + Date () + '\n'
            var new_txt = txt.substring (0, selStart) + date_str + txt.substring (selEnd, txt.length);
            TextAreaControl.value =  new_txt;
            TextAreaControl.selectionStart = selStart;
            TextAreaControl.selectionEnd = selStart + date_str.length;

        }

        function enable_delete_file ()
        {
            var DeleteButton = document.getElementById ('delete_file_btn');
            var Checkbox = document.getElementById ('enable_delete_chkbox');
          //  alert("latent_href = " + DeleteButton.getAttribute ('latent_href'))

            if (Checkbox.checked) {
              DeleteButton.removeAttribute ('disabled');
              DeleteButton.setAttribute ('href', DeleteButton.getAttribute ('latent_href'));

            } else {

              DeleteButton.setAttribute ('disabled', true);
              DeleteButton.removeAttribute ('href');
            }

        }




     </script>
  </body>
</html>