django_fc/django_fc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django_fc import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url (r"^delete_project/", views.delete_project, name = 'delete_project'),
    url (r"^edit_project/", views.edit_project, name = 'edit_project'),
    url (r"^toggle_mode/", views.toggle_stt_session_mode, name = 'toggle_mode'),
    url (r"^edit_settings/", views.edit_settings, name = 'edit_settings'),
    url(r"^select_project/(?P<name>[^\"*]*)", views.select_project, name="select_project"),
    url(r"^new_project/", views.new_project, name="new_project"),
    url(r"^fw_move_back/", views.fw_move_back, name="fw_move_back"),
    url(r"^fw_move_forward/", views.fw_move_forward, name="fw_move_forward"),
    url(r"^fw_move_to_start/", views.fw_move_to_start, name="fw_move_to_start"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^$", views.HomePage.as_view(), name="home"),

    url(r"^fcards/", include ('fcards.urls', namespace='fcards')),
    url(r"^upload/", include ('upload.urls', namespace='upload')),
    url(r"^text/"  , include ('text.urls'  , namespace='text')),


]

django_fc/fcards/urls.py
from django.conf.urls import url

from . import views

app_name='fcards'

urlpatterns = [

    url(r"^start_session_randold/$",views.start_session_randold,name="start_session_randold"),
    url(r"^start_session_all/$",views.start_session_all,name="start_session_all"),
    url(r"^start_session_dated/(?P<date>.+)/", views.start_session_dated, name="start_session_dated"),
    url(r"^start_session_intervalled/(?P<start>.+)/(?P<size>.+)", views.start_session_intervalled, name="start_session_intervalled"),
    url(r"^start_session_intervalled_random/(?P<start>.+)/(?P<size>.+)", views.start_session_intervalled_random, name="start_session_intervalled_random"),
    url(r"^roll_back/$",views.roll_back,name="roll_back"),
    url(r"^roll_forward/$",views.roll_forward,name="roll_forward"),
    url(r"^user_guessing/$",views.UserGuessing.as_view(),name="user_guessing"),
    url(r"^awaiting_approval/$",views.AwaitingApproval.as_view(),name="awaiting_approval"),
    url(r"^approve_btn/$", views.ApproveButtonOnClick.as_view(), name="approve_btn_on_click"),
    url(r"^dont_approve_btn/$", views.DontApproveButtonOnClick.as_view (), name="dont_approve_btn_on_click"),
    url(r"^edit_btn/$", views.edit_btn_on_click, name="edit_btn_on_click"),
    url(r"^end_of_session/$", views.end_of_session, name="end_of_session"),
    url(r"^restart_session/$", views.restart_session_in_other_mode, name="restart_session"),
    url(r"^resume_session/$", views.funnel, name="funnel"),
    url(r"^resume_session/$", views.resume_session, name="resume_session"),
    url(r"^end_session_done/$", views.end_session_done, name="end_session_done"),

]

django_fc/text/urls.py
from django.conf.urls import url

from . import views

app_name='text'

urlpatterns = [
    url(r"^generate_src_file/", views.generate_src_file, name="generate_src_file"),
    url(r"^download_source_file/(?P<file_name>[^\"*]*)", views.download_source_file, name="download_source_file"),
    url(r"^work_with_text/(?P<file_name>[^\"*]*)", views.work_with_text, name="work_with_text"),
    url(r"^delete_file/(?P<file_name>[^\"*]+)/", views.delete_file, name="delete_file"),
    url(r"^save_file/(?P<file_name>[^\"*]+)/", views.save_file, name="save_file"),
]

django_fc/fcards/forms.py
from django import forms

class EditVocEntryForm (forms.Form):

    def __init__(self, vdbe, *args, **kwargs):
        super(EditVocEntryForm, self).__init__(*args, **kwargs)
        # dynamic fields here ...

        short_txt_widget = forms.TextInput (
                attrs = {
                    'class' : 'form-control',
                }
        )
        long_txt_widget = forms.Textarea (
                attrs = {
                    'class' : 'form-control',
                    'rows' : 2,
                }
        )

        self.fields ['lemma_ID'] = forms.CharField (initial=vdbe.lemma_ID, widget=short_txt_widget)
        self.fields ['lft_lemma_ID'] = forms.CharField (initial=vdbe.lft_lemma_ID, widget=short_txt_widget)
        self.fields ['lft_usage_ID'] = forms.CharField (initial=vdbe.lft_usage_ID, widget=short_txt_widget)

        self.fields ['rgt_lemma_ID'] = forms.CharField (initial=vdbe.rgt_lemma_ID, widget=short_txt_widget)
        self.fields ['rgt_usage_ID'] = forms.CharField (initial=vdbe.rgt_usage_ID, widget=short_txt_widget)

        self.fields ['lft_lemma_display'] = forms.CharField (initial=vdbe.lft_lemma_display, widget=short_txt_widget)
        self.fields ['rgt_lemma_display'] = forms.CharField (initial=vdbe.rgt_lemma_display, widget=short_txt_widget)

        citL = vdbe.get_citL ()
        ctxL = vdbe.get_ctxL ()


        self.fields ['ctx 0'] = forms.CharField(initial= ctxL [0], label = 'Context', widget=long_txt_widget)

        for ii in range (len (citL)):
            self.fields ['cit ' + str (ii) ] = forms.CharField (initial=citL [ii], label = 'Citation', widget=short_txt_widget)
            self.fields ['ctx ' + str (ii + 1) ] = forms.CharField (initial = ctxL [ii + 1], label = 'Context', widget=long_txt_widget)


    # normal fields here ...

    def to_vdbe (self, vdbe):

        data = self. cleaned_data
        print (data)
        vdbe.rgt_lemma_ID = data ['rgt_lemma_ID']
        vdbe.rgt_lemma_display = data ['rgt_lemma_display']
        vdbe.rgt_usage_ID = data ['rgt_usage_ID']

        vdbe.lft_lemma_ID = data ['lft_lemma_ID']
        vdbe.lft_lemma_display = data ['lft_lemma_display']
        vdbe.lft_usage_ID = data ['lft_usage_ID']

        vdbe.lemma_ID = data['lemma_ID']
    #    vdbe.correct_answer = data ['correct_answer']

        citL = []
        ctxL = []
        for field, value in data.items ():
            spl = field.split (' ')
            if len (spl) == 2 and spl [1].isdigit ():
                ind = int (spl [1])
                if spl [0] == 'cit':
                    citL.append ((ind, value))
                else:
                    ctxL.append ((ind, value))

        citL.sort ()
        ctxL.sort ()

        citL = [item [1] for  item in citL]
        ctxL = [item [1] for item in ctxL]
        vdbe.cits = '|'.join (citL)
        vdbe.ctxs = '|'.join (ctxL)
        print (vdbe.cits)
        print (vdbe.ctxs)

django_fc/fcards/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic import TemplateView, FormView, RedirectView
from django.urls import reverse

from . import models
from .models import FCSettings
from .models import ProcessedInPast

from fc_engine.back_end import session
from fc_engine.settings import Settings

from django.contrib.auth import get_user_model
User = get_user_model()





def roll_back (request):

    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.roll_back ()
    request.session ['ss'] = ss.to_json ()

    return HttpResponseRedirect(reverse('fcards:user_guessing'))

def roll_forward (request):

    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.roll_forward ()
    request.session ['ss'] = ss.to_json ()

    return HttpResponseRedirect(reverse('fcards:user_guessing'))

def start_session_randold (request):

    stt = Settings ()
    stt.from_json (request.session ['stt'])

    project_id = request.session ['project_id']
    all_voc = models.all_to_dbvoc (request.user.id, project_id)

    idL = all_voc.get_dated_idL_given_date_ind ((0, -2))

    ss = session ()
    """
    print ('mydebug>>>> start_session_randold : calling ss.start')
    print ()
    print (idL)
    print ()
    """
    if ss.start (stt, all_voc, idL, stt.lessons.rand_old):

        request.session ['ss']      =  ss.to_json ()

        return HttpResponseRedirect(reverse('fcards:user_guessing'))
    else:
        return HttpResponseRedirect (reverse('home'))


def start_session_all (request):

    stt = Settings ()
    stt.from_json (request.session ['stt'])

    project_id = request.session ['project_id']
    all_voc = models.all_to_dbvoc (request.user.id, project_id)

    idL = all_voc.get_idL ()

    ss = session ()
    if ss.start (stt, all_voc, idL):

        #eng = engine ()
        #eng.start ()

        #request.session ['eng']     =  eng.to_json ()

        #request.session ['all_voc'] =  all_voc.to_json ()
        request.session ['ss']      =  ss.to_json ()



        return HttpResponseRedirect(reverse('fcards:user_guessing'))
    else:
        return HttpResponseRedirect (reverse('home'))

def start_session_dated (request, *args, **kwargs):

    stt = Settings ()
    stt.from_json (request.session ['stt'])

    #index = int (kwargs ['index']) - 1

    date  = kwargs  ['date']

    project_id = request.session ['project_id']
    all_voc = models.all_to_dbvoc (request.user.id, project_id)
#    idL = all_voc.get_dated_idL (index)
    idL = all_voc.get_dated_idL (date)

    ss = session ()
    if ss.start (stt, all_voc, idL):

        #eng.start ()
        #request.session ['eng']     =  eng.to_json ()
        #request.session ['all_voc'] =  all_voc.to_json ()
        request.session ['ss']      =  ss.to_json ()

        return HttpResponseRedirect(reverse('fcards:user_guessing'))
    else:
        return HttpResponseRedirect (reverse('home'))


def start_session_intervalled (request, *args, **kwargs):

    stt = Settings ()
    #print (request.session ['stt'])
    stt.from_json (request.session ['stt'])
    #print ("start_session_intervalled:::: stt.randomize = {}".format (stt.session.randomize))

    #index = int (kwargs ['index']) - 1

    start  = int (kwargs  ['start'])
    size = int (kwargs ['size'])

    project_id = request.session ['project_id']
    all_voc = models.all_to_dbvoc (request.user.id, project_id)
#    idL = all_voc.get_dated_idL (index)

    idL = all_voc.get_intervalled_idL (start, size)

    ss = session ()
    if ss.start (stt, all_voc, idL):

        #eng.start ()
        #request.session ['eng']     =  eng.to_json ()
        #request.session ['all_voc'] =  all_voc.to_json ()
        request.session ['ss']      =  ss.to_json ()

        return HttpResponseRedirect(reverse('fcards:user_guessing'))
    else:
        return HttpResponseRedirect (reverse('home'))


def start_session_intervalled_random (request, *args, **kwargs):

    stt = Settings ()
    stt.from_json (request.session ['stt'])

    #index = int (kwargs ['index']) - 1

    start  = int (kwargs  ['start'])
    size = int (kwargs ['size'])

    project_id = request.session ['project_id']
    all_voc = models.all_to_dbvoc (request.user.id, project_id)
#    idL = all_voc.get_dated_idL (index)

    idL = all_voc.get_intervalled_idL (start, size)

    ss = session ()
    if ss.start (stt, all_voc, idL, stt.lessons.rand_old):

        #eng.start ()
        #request.session ['eng']     =  eng.to_json ()
        #request.session ['all_voc'] =  all_voc.to_json ()
        request.session ['ss']      =  ss.to_json ()

        return HttpResponseRedirect(reverse('fcards:user_guessing'))
    else:
        return HttpResponseRedirect (reverse('home'))



def end_of_session (request):


    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.end ()


    stats = dict ()

    stats ['kills'] = "Total words processed: {}".format (ss.stats.kills)
    stats ['clean_kills'] = "First try guesses: {}".format (ss.stats.clean_kills)
    if ss.stats.alive == 0 and ss.stats.kills == ss.stats.clean_kills:
        stats ['congrats'] = "*** Congrats!!! ***"
    elif ss.stats.alive > 0:
        stats ['yet_to_process'] = "Total words yet to process: {}".format (ss.stats.alive)
        stats ['yet_untouched'] = "Total words yet untouched: {}".format (ss.stats.untouched)

    stt = Settings ()
    stt.from_json (request.session ['stt'])
    if stt.session.mode == 'generation':
        other_fc_mode = 'recognition'
    else:
        other_fc_mode = 'generation'

    stats ['other_fc_mode'] = other_fc_mode

    request.session ['ss'] = ss.to_json ()

    return render(request, 'end_of_session.html', context=stats)



def restart_session_in_other_mode (request):

    stt = Settings ()
    stt.from_json (request.session ['stt'])
    if stt.session.mode == 'generation':
        stt.session.mode = 'recognition'
    else:
        stt.session.mode = 'generation'
    request.session ['stt'] = stt.to_json ()

    project_id = request.session ['project_id']

    dbst = FCSettings.objects.filter (user_id=request.user.id).get(project_id=project_id)
    dbst.from_stt (stt)
    dbst.save ()


    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.restart ()
    request.session ['ss'] = ss.to_json ()

    return HttpResponseRedirect(reverse('fcards:user_guessing'))




def end_session_done (request):

    ss = session ()
    ss.from_json (request.session ['ss'])

    idS = ss.register_dead ()

    project_id = request.session ['project_id']
    user_id = request.user.id

    for id in idS:

        # find entry (ID)
        vdbe = get_vdbe (id)
        lemma_ID = vdbe.lft_lemma_ID + '__' + vdbe.rgt_lemma_ID

        try :
            #dbst = FCSettings.objects.filter (user_id=request.user.id).get(project_id=project_id)
            pip = ProcessedInPast.objects.filter (user_id=request.user.id, project_id=project_id).get (lemma_ID=lemma_ID)

#            pip = ooo.get (lemma_ID=lemma_ID)
            pip.times_processed += 1
            print ("========= pip don't exist ================")

        except models.ProcessedInPast.DoesNotExist:
            pip = ProcessedInPast ()
            pip.user_id = user_id
            pip.project_id = project_id
            pip.lemma_ID = lemma_ID
            pip.times_processed = 1

        print ("............. Saving Pip (((((((((((())))))))))))")
        pip.save ()

    return HttpResponseRedirect(reverse('home'))


def resume_session (request):

    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.resume ()
    request.session ['ss'] = ss.to_json ()

    return HttpResponseRedirect(reverse('fcards:user_guessing'))

def funnel (request):

    ss = session ()
    ss.from_json (request.session ['ss'])
    ss.funnel ()
    request.session ['ss'] = ss.to_json ()

    return HttpResponseRedirect(reverse('fcards:user_guessing'))



from  . import forms
from .models import VocEntry, get_vdbe, Project

def edit_btn_on_click (request):

    stt = Settings ()
    stt.from_json (request.session ['stt'])
    ss = session ()
    ss.from_json (request.session ['ss'])
    project_id = request.session ['project_id']
    project_obj = Project.objects.filter (user_id=request.user.id).get (id=project_id)
    language_id = project_obj.language_id

    #all_voc = dbVoc ()
    #all_voc.from_json (request.session ['all_voc'])

    #vdbe = all_voc.get_voc_entry (str (ss.get_cur_entry_ID ()))
    vdbe = get_vdbe (ss.get_cur_entry_ID ())

    form = forms.EditVocEntryForm (vdbe)

    if request.method == 'POST':
        form = forms.EditVocEntryForm (vdbe, request.POST)
        if form.is_valid ():
            form.to_vdbe (vdbe)
            ve = models.VocEntry ()
            ve.from_vdbe (vdbe)
            ve.id = vdbe.ID
            ve.user_id = request.user.id
            ve.project_id = project_id
            ve.language_id = language_id

    #        request.session ['all_voc'] =  all_voc.to_json ()

            ve.save ()
            return  HttpResponseRedirect (reverse ("fcards:awaiting_approval"))

    return render (request, 'edit_entry.html', {'form':form})




class UserGuessing (TemplateView):
    template_name = 'user_guessing.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)

        stt = Settings ()
        stt.from_json (self.request.session ['stt'])

        #all_voc = dbVoc ()
        #all_voc.from_json (self.request.session ['all_voc'])
        ss = session ()
        ss.from_json (self.request.session ['ss'])

        #print ("mydebug >>> views.UserGuessing eng.running : {}".format (eng.running))

        #vdbe = all_voc.get_voc_entry (str (ss.get_cur_entry_ID()))
        vdbe = get_vdbe (ss.get_cur_entry_ID ())

django_fc/fcards/templates/awaiting_approval.html
{% extends "fcards_base.html" %}
{% block content %}

<div class="jumbodtron">

  <p>Words yet to process (including this one): {{ session_size }}</p>
  <p>Required hit number for this word:         {{ rhn }}</p>
  
  <div class="row">
    <div class="col-md-9">

      <h2> {{ answer|safe }} </h2>
      <h2> {{ context|safe }} </h2>
    </div>
    <div class="col-md-3">
      <h1>
        <p>
          <a href="{% url 'fcards:approve_btn_on_click' %}" class="btn btn-success">Success</a>
          <a href="{% url 'fcards:dont_approve_btn_on_click' %}" class="btn btn-primary">Ask me again later</a></p>
      </h1>
      <h3><a href="{% url 'fcards:edit_btn_on_click' %}">Edit entry</a></h3>
    </div>
</div>


{% endblock %}

django_fc/fcards/templates/edit_entry.html
{% extends "fcards_base.html" %}
{% block content %}

<div class="jumbodtron">

  <div class="container">
    <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
        <a href="{% url 'fcards:awaiting_approval' %}" class="btn btn-primary">Cancel</a>

    </form>
  </div>


</div>


{% endblock %}

django_fc/fcards/templates/end_of_session.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Flashcards</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


  </head>


  <body>

<div class="container mycontent">

<div class="jumbodtron">

  <h2>Results:</h2>

  <h2> {{ kills }} </h2>
  <h2> {{ clean_kills }} </h2>
  {% if congrats %}
     <h2> {{ congrats }} </h2>
  {% endif %}

  {% if yet_to_process %}
    <h2> {{ yet_to_process }} </h2>
    <h2> {{ yet_untouched }} </h2>
  {% endif %}


      </div>

      {% if yet_to_process %}
        <a href="{% url 'fcards:resume_session' %}" class="btn btn-primary">Resume session</a>
      {% endif %}
      <a href="{% url 'fcards:restart_session' %}" class="btn btn-primary">Redo same session in {{ other_fc_mode }} mode</a>

      {% if not congrats %}
        <h1>
          <a href="{% url 'fcards:funnel' %}" class="btn btn-primary">Funnel</a>
        </h1>

        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
      {% endif %}

      <h1>
        <a href="{% url 'home' %}" class="btn btn-primary"> Done </a>
      </h1>
</div>

  </body>
</html>

django_fc/fcards/templates/fcards_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Flashcards</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static "fcards/styles.css" %}">

  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">
            <a class="navbar-brand mynav" href="{% url 'fcards:end_of_session' %}">End Session</a>

            <ul class="nav navbar-nav navbar-right">
                <li><a class="navbar-brand mynav" href="{% url 'fcards:roll_back' %}">Roll Back</a></li>
                <li><a class="navbar-brand mynav" href="{% url 'fcards:roll_forward' %}">Roll Forward</a></li>
            </ul>


    	</div>
    </nav>


    <div class="container mycontent">


      {% block content %}

      {% endblock %}

    </div>


  </body>
</html>

django_fc/fcards/templates/user_guessing.html
{% extends "fcards_base.html" %}
{% block content %}

<div class="jumbodtron">
  <p>Words yet to process (including this one): <span class=number> {{ session_size }}</span></p>
  <p>Required hit number for this word:         <span class=number> {{ rhn }}</span></p>
  <p></p>

  <div class="row">
    <div class="col-md-9">
       <h2> {{ question|safe }}</h2>
       <h2> {{ context|safe }} </h2>
    </div>
    <div class="col-md-3">

      <h1>
        <a href="{% url 'fcards:awaiting_approval' %}" class="btn  btn-primary"> Show correct answer </a>
      </h1>
    </div>
  </div>
  </div>


</div>

{% endblock %}